apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: hotrod
  name: hotrod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hotrod
  strategy: {}
  template:
    metadata:
      labels:
        app: hotrod
    spec:
      containers:
      - image: hotrod-hotrod
        name: hotrod
        imagePullPolicy: Never
        args: ["all"]
        env:
          - name: PYROSCOPE_APPLICATION_NAME
            value: hotrod
          - name: PYROSCOPE_SERVER_ADDRESS
            value: "http://pyroscope-server.default.svc.cluster.local:4040"
        ports:
          - containerPort: 8080
            name: frontend
          - containerPort: 8081
            name: customer
          - containerPort: 8083
            name: route
        resources:
          limits:
            cpu: 100m
            memory: 100M
          requests:
            cpu: 100m
            memory: 100M
